/* 
===================================================================
OFFICIAL COMPETITION QUESTIONS
===================================================================
Source: Think_Quest_Competition_Quiz_Set_September_25_2026_REVISED.docx
DO NOT COMMIT THIS FILE TO A PUBLIC GITHUB REPOSITORY.
===================================================================
*/

const quizData = {
    trial: [
        {
            id: "T1",
            round: "trial",
            roundTitle: "Trial Questions",
            questionNumber: 1,
            subjectArea: "Mathematics",
            specificTopic: "Order of operations",
            difficulty: "Easy",
            cognitiveSkill: "Application",
            questionType: "multiple-choice",
            timeLimit: 10,
            points: 0,
            question: "Evaluate 6 + 2 × 3.",
            options: {
                A: "24",
                B: "12",
                C: "18",
                D: "8"
            },
            correctAnswer: "12",
            correctOption: "B",
            acceptedAlternativeAnswers: [],
            explanation: "Multiplication comes first: 2 × 3 = 6, then 6 + 6 = 12. A multiplies the sum; C and D result from incorrect operations.",
            quizMasterNote: "None.",
            sourceTitle: "Elementary Algebra 2e",
            sourceInstitution: "OpenStax, Rice University",
            sourceDate: "2020",
            sourceLink: "https://openstax.org/details/books/elementary-algebra-2e"
        },
        {
            id: "T2",
            round: "trial",
            roundTitle: "Trial Questions",
            questionNumber: 2,
            subjectArea: "Science and Technology",
            specificTopic: "Biology",
            difficulty: "Easy",
            cognitiveSkill: "Recall",
            questionType: "identification",
            timeLimit: 10,
            points: 0,
            question: "What organelle contains most of a eukaryotic cell’s genetic material?",
            options: null,
            correctAnswer: "Nucleus",
            correctOption: null,
            acceptedAlternativeAnswers: [],
            explanation: "The nucleus houses most eukaryotic DNA. Mitochondria contain a small separate genome but not most cellular genetic material.",
            quizMasterNote: "None.",
            sourceTitle: "Biology 2e",
            sourceInstitution: "OpenStax, Rice University",
            sourceDate: "2020",
            sourceLink: "https://openstax.org/details/books/biology-2e"
        },
        {
            id: "T3",
            round: "trial",
            roundTitle: "Trial Questions",
            questionNumber: 3,
            subjectArea: "Arts and Literature",
            specificTopic: "Literary form",
            difficulty: "Easy",
            cognitiveSkill: "Recognition",
            questionType: "multiple-choice",
            timeLimit: 10,
            points: 0,
            question: "Which literary form is a long narrative poem about heroic deeds?",
            options: {
                A: "Sonnet",
                B: "Elegy",
                C: "Epic",
                D: "Haiku"
            },
            correctAnswer: "Epic",
            correctOption: "C",
            acceptedAlternativeAnswers: [],
            explanation: "An epic is a long heroic narrative poem. A sonnet is a 14-line lyric form; an elegy laments; a haiku is a brief Japanese form.",
            quizMasterNote: "None.",
            sourceTitle: "Epic",
            sourceInstitution: "Encyclopaedia Britannica",
            sourceDate: "No date shown",
            sourceLink: "https://www.britannica.com/art/epic"
        }
    ],
    round1: [
        {
            id: "R1-1",
            round: "round1",
            roundTitle: "Once and For All",
            questionNumber: 1,
            subjectArea: "Arts and Literature",
            specificTopic: "Art appreciation—chiaroscuro",
            difficulty: "Easy",
            cognitiveSkill: "Recall and recognition",
            questionType: "multiple-choice",
            timeLimit: 10,
            points: 1,
            question: "What art term refers to the use of strong contrasts of light and dark to model three-dimensional form?",
            options: {
                A: "Chiaroscuro",
                B: "Collage",
                C: "Impasto",
                D: "Pointillism"
            },
            correctAnswer: "Chiaroscuro",
            correctOption: "A",
            acceptedAlternativeAnswers: [],
            explanation: "Chiaroscuro models form through light and shadow. Collage attaches materials; impasto uses thick paint; pointillism uses dots of color.",
            quizMasterNote: "None.",
            sourceTitle: "Chiaroscuro",
            sourceInstitution: "Encyclopaedia Britannica",
            sourceDate: "No date shown",
            sourceLink: "https://www.britannica.com/art/chiaroscuro"
        },
        {
            id: "R1-2",
            round: "round1",
            roundTitle: "Once and For All",
            questionNumber: 2,
            subjectArea: "Social Sciences",
            specificTopic: "Sociology",
            difficulty: "Easy",
            cognitiveSkill: "Recall and recognition",
            questionType: "multiple-choice",
            timeLimit: 10,
            points: 1,
            question: "Which discipline systematically studies societies, groups, and social interaction?",
            options: {
                A: "Archaeology",
                B: "Sociology",
                C: "Linguistics",
                D: "Geography"
            },
            correctAnswer: "Sociology",
            correctOption: "B",
            acceptedAlternativeAnswers: [],
            explanation: "Sociology studies societies and social interaction. Archaeology studies material remains; linguistics studies language; geography studies places and spatial relationships.",
            quizMasterNote: "None.",
            sourceTitle: "1.1 What Is Sociology?",
            sourceInstitution: "OpenStax, Rice University",
            sourceDate: "2021",
            sourceLink: "https://openstax.org/books/introduction-sociology-3e/pages/1-1-what-is-sociology"
        },
        {
            id: "R1-3",
            round: "round1",
            roundTitle: "Once and For All",
            questionNumber: 3,
            subjectArea: "Mathematics",
            specificTopic: "Basic statistics—median",
            difficulty: "Easy",
            cognitiveSkill: "Application",
            questionType: "multiple-choice",
            timeLimit: 10,
            points: 1,
            question: "What is the median of 3, 5, 8, 9, and 12?",
            options: {
                A: "5",
                B: "7",
                C: "8",
                D: "9"
            },
            correctAnswer: "8",
            correctOption: "C",
            acceptedAlternativeAnswers: [],
            explanation: "The ordered list has five values, so its middle or third value is 8. The other options are not the central observation.",
            quizMasterNote: "None.",
            sourceTitle: "Introductory Statistics 2e",
            sourceInstitution: "OpenStax, Rice University",
            sourceDate: "2023",
            sourceLink: "https://openstax.org/details/books/introductory-statistics-2e"
        },
        {
            id: "R1-4",
            round: "round1",
            roundTitle: "Once and For All",
            questionNumber: 4,
            subjectArea: "Science and Technology",
            specificTopic: "Chemistry—atomic structure",
            difficulty: "Easy",
            cognitiveSkill: "Recall and recognition",
            questionType: "multiple-choice",
            timeLimit: 10,
            points: 1,
            question: "Which subatomic particle determines an element’s atomic number?",
            options: {
                A: "Electron",
                B: "Neutron",
                C: "Photon",
                D: "Proton"
            },
            correctAnswer: "Proton",
            correctOption: "D",
            acceptedAlternativeAnswers: [],
            explanation: "The atomic number equals the number of protons. Electrons determine net charge, neutrons distinguish isotopes, and photons are quanta of electromagnetic radiation.",
            quizMasterNote: "None.",
            sourceTitle: "Fundamentals of Physics and Chemistry Important to Microbiology",
            sourceInstitution: "OpenStax, Rice University",
            sourceDate: "2016",
            sourceLink: "https://openstax.org/books/microbiology/pages/a-fundamentals-of-physics-and-chemistry-important-to-microbiology"
        },
        {
            id: "R1-5",
            round: "round1",
            roundTitle: "Once and For All",
            questionNumber: 5,
            subjectArea: "General Information",
            specificTopic: "Blue Ghost Mission 1 lunar landing",
            difficulty: "Easy",
            cognitiveSkill: "Recall and recognition",
            questionType: "multiple-choice",
            timeLimit: 10,
            points: 1,
            question: "On March 2, 2025, which company’s Blue Ghost Mission 1 successfully landed on the Moon carrying NASA instruments?",
            options: {
                A: "Firefly Aerospace",
                B: "SpaceX",
                C: "Blue Origin",
                D: "Rocket Lab"
            },
            correctAnswer: "Firefly Aerospace",
            correctOption: "A",
            acceptedAlternativeAnswers: [],
            explanation: "Firefly Aerospace operated Blue Ghost Mission 1. The other companies did not operate this lander. Event date: March 2, 2025.",
            quizMasterNote: "None.",
            sourceTitle: "Touchdown! Carrying NASA Science, Firefly’s Blue Ghost Lands on Moon",
            sourceInstitution: "NASA",
            sourceDate: "March 2, 2025",
            sourceLink: "https://www.olympics.com/en/olympic-games/paris-2024"
        },
        {
            id: "R1-6",
            round: "round1",
            roundTitle: "Once and For All",
            questionNumber: 6,
            subjectArea: "Arts and Literature",
            specificTopic: "World literature—magic realism",
            difficulty: "Easy",
            cognitiveSkill: "Recognition",
            questionType: "multiple-choice",
            timeLimit: 10,
            points: 1,
            question: "Which literary mode presents fantastic events as ordinary parts of an otherwise realistic world?",
            options: {
                A: "Naturalism",
                B: "Magic realism",
                C: "Classicism",
                D: "Sentimentalism"
            },
            correctAnswer: "Magic realism",
            correctOption: "B",
            acceptedAlternativeAnswers: ["Magical realism"],
            explanation: "Magic realism treats fantastic or mythical elements matter-of-factly within realistic fiction. The other movements do not have this defining combination.",
            quizMasterNote: "None.",
            sourceTitle: "Magic realism",
            sourceInstitution: "Encyclopaedia Britannica",
            sourceDate: "August 28, 2026",
            sourceLink: "https://www.britannica.com/art/magic-realism"
        },
        {
            id: "R1-7",
            round: "round1",
            roundTitle: "Once and For All",
            questionNumber: 7,
            subjectArea: "Social Sciences",
            specificTopic: "Anthropology",
            difficulty: "Easy",
            cognitiveSkill: "Recall and recognition",
            questionType: "multiple-choice",
            timeLimit: 10,
            points: 1,
            question: "Which social science studies humanity across time and space?",
            options: {
                A: "Economics",
                B: "Psychology",
                C: "Anthropology",
                D: "Political science"
            },
            correctAnswer: "Anthropology",
            correctOption: "C",
            acceptedAlternativeAnswers: [],
            explanation: "Anthropology studies humanity across time and space. Economics studies allocation, psychology behavior and mental processes, and political science politics and government.",
            quizMasterNote: "None.",
            sourceTitle: "1.1 The Study of Humanity",
            sourceInstitution: "OpenStax, Rice University",
            sourceDate: "2022",
            sourceLink: "https://openstax.org/books/introduction-anthropology/pages/1-1-the-study-of-humanity-or-anthropology-is-vast"
        },
        {
            id: "R1-8",
            round: "round1",
            roundTitle: "Once and For All",
            questionNumber: 8,
            subjectArea: "Mathematics",
            specificTopic: "Basic statistics—mean",
            difficulty: "Easy",
            cognitiveSkill: "Application",
            questionType: "multiple-choice",
            timeLimit: 10,
            points: 1,
            question: "What is the arithmetic mean of 4, 6, 8, and 10?",
            options: {
                A: "6",
                B: "6.5",
                C: "8",
                D: "7"
            },
            correctAnswer: "7",
            correctOption: "D",
            acceptedAlternativeAnswers: [],
            explanation: "The sum is 28 and 28 ÷ 4 = 7. The distractors arise from selecting a data value or dividing incorrectly.",
            quizMasterNote: "None.",
            sourceTitle: "Introductory Statistics 2e",
            sourceInstitution: "OpenStax, Rice University",
            sourceDate: "2023",
            sourceLink: "https://openstax.org/details/books/introductory-statistics-2e"
        },
        {
            id: "R1-9",
            round: "round1",
            roundTitle: "Once and For All",
            questionNumber: 9,
            subjectArea: "Science and Technology",
            specificTopic: "Earth science—earthquakes",
            difficulty: "Easy",
            cognitiveSkill: "Recall and recognition",
            questionType: "identification",
            timeLimit: 10,
            points: 1,
            question: "What is the point on Earth’s surface directly above an earthquake’s hypocenter?",
            options: null,
            correctAnswer: "Epicenter",
            correctOption: null,
            acceptedAlternativeAnswers: [],
            explanation: "The epicenter is the surface location directly above the hypocenter, where rupture begins underground.",
            quizMasterNote: "None.",
            sourceTitle: "The Science of Earthquakes",
            sourceInstitution: "U.S. Geological Survey",
            sourceDate: "Updated January 18, 2024",
            sourceLink: "https://www.usgs.gov/programs/earthquake-hazards/science-earthquakes"
        },
        {
            id: "R1-10",
            round: "round1",
            roundTitle: "Once and For All",
            questionNumber: 10,
            subjectArea: "General Information",
            specificTopic: "2024 Nobel Prize in Literature",
            difficulty: "Easy",
            cognitiveSkill: "Recall and recognition",
            questionType: "identification",
            timeLimit: 10,
            points: 1,
            question: "Who was announced as the 2024 Nobel Prize laureate in Literature on October 10, 2024?",
            options: null,
            correctAnswer: "Han Kang",
            correctOption: null,
            acceptedAlternativeAnswers: [],
            explanation: "The Swedish Academy awarded the 2024 Nobel Prize in Literature to South Korean author Han Kang. Event date: October 10, 2024.",
            quizMasterNote: "None.",
            sourceTitle: "All Nobel Prizes 2024",
            sourceInstitution: "Nobel Prize Outreach",
            sourceDate: "2024",
            sourceLink: "https://www.nobelprize.org/all-nobel-prizes-2024/"
        }
    ],
    round2: [
        {
            id: "R2-1",
            round: "round2",
            roundTitle: "Double the Fun",
            questionNumber: 1,
            subjectArea: "Arts and Literature",
            specificTopic: "Art appreciation—Cubism",
            difficulty: "Moderate",
            cognitiveSkill: "Analysis and comparison",
            questionType: "multiple-choice",
            timeLimit: 15,
            points: 2,
            question: "A painting fragments a violin into overlapping geometric planes and shows it from several viewpoints at once. Which movement best fits the description?",
            options: {
                A: "Impressionism",
                B: "Surrealism",
                C: "Cubism",
                D: "Romanticism"
            },
            correctAnswer: "Cubism",
            correctOption: "C",
            acceptedAlternativeAnswers: [],
            explanation: "Cubism fragments objects and presents multiple viewpoints on a flat plane. Impressionism stresses fleeting light, Surrealism dreamlike imagery, and Romanticism emotion and sublimity.",
            quizMasterNote: "None.",
            sourceTitle: "Cubism",
            sourceInstitution: "Encyclopaedia Britannica",
            sourceDate: "July 29, 2026",
            sourceLink: "https://www.britannica.com/art/Cubism"
        },
        {
            id: "R2-2",
            round: "round2",
            roundTitle: "Double the Fun",
            questionNumber: 2,
            subjectArea: "Social Sciences",
            specificTopic: "Economics—opportunity cost",
            difficulty: "Moderate",
            cognitiveSkill: "Application",
            questionType: "multiple-choice",
            timeLimit: 15,
            points: 2,
            question: "A student can spend Saturday either reviewing for an exam or earning 800 pesos at a one-day job. If the student reviews, what is the opportunity cost stated in the problem?",
            options: {
                A: "The exam grade",
                B: "The cost of review materials",
                C: "Saturday itself",
                D: "The 800-peso earnings forgone"
            },
            correctAnswer: "The 800-peso earnings forgone",
            correctOption: "D",
            acceptedAlternativeAnswers: [],
            explanation: "Opportunity cost is the value of the best alternative forgone: the 800-peso job. The other choices are not the specified sacrificed alternative.",
            quizMasterNote: "None.",
            sourceTitle: "Principles of Economics 3e, Chapter 2",
            sourceInstitution: "OpenStax, Rice University",
            sourceDate: "2022",
            sourceLink: "https://openstax.org/books/principles-economics-3e/pages/2-introduction-to-choice-in-a-world-of-scarcity"
        },
        {
            id: "R2-3",
            round: "round2",
            roundTitle: "Double the Fun",
            questionNumber: 3,
            subjectArea: "Mathematics",
            specificTopic: "Probability without replacement",
            difficulty: "Moderate",
            cognitiveSkill: "Application",
            questionType: "multiple-choice",
            timeLimit: 15,
            points: 2,
            question: "A bag contains 3 red and 2 blue marbles. Two marbles are drawn without replacement. What is the probability that both are blue?",
            options: {
                A: "1/10",
                B: "1/5",
                C: "2/5",
                D: "1/4"
            },
            correctAnswer: "1/10",
            correctOption: "A",
            acceptedAlternativeAnswers: [],
            explanation: "The probability is (2/5)(1/4) = 2/20 = 1/10. The other fractions do not account correctly for drawing without replacement.",
            quizMasterNote: "None.",
            sourceTitle: "Introductory Statistics 2e",
            sourceInstitution: "OpenStax, Rice University",
            sourceDate: "2023",
            sourceLink: "https://openstax.org/details/books/introductory-statistics-2e"
        },
        {
            id: "R2-4",
            round: "round2",
            roundTitle: "Double the Fun",
            questionNumber: 4,
            subjectArea: "Science and Technology",
            specificTopic: "Chemistry—ions",
            difficulty: "Moderate",
            cognitiveSkill: "Application",
            questionType: "multiple-choice",
            timeLimit: 15,
            points: 2,
            question: "A neutral atom has 11 protons. After losing one electron, what are its net charge and number of electrons?",
            options: {
                A: "−1 and 12",
                B: "+1 and 10",
                C: "+1 and 11",
                D: "0 and 10"
            },
            correctAnswer: "+1 and 10",
            correctOption: "B",
            acceptedAlternativeAnswers: [],
            explanation: "A neutral 11-proton atom has 11 electrons. Losing one leaves 10 electrons and one excess positive charge.",
            quizMasterNote: "None.",
            sourceTitle: "Fundamentals of Physics and Chemistry Important to Microbiology",
            sourceInstitution: "OpenStax, Rice University",
            sourceDate: "2016",
            sourceLink: "https://openstax.org/books/microbiology/pages/a-fundamentals-of-physics-and-chemistry-important-to-microbiology"
        },
        {
            id: "R2-5",
            round: "round2",
            roundTitle: "Double the Fun",
            questionNumber: 5,
            subjectArea: "General Information",
            specificTopic: "WHO Pandemic Agreement",
            difficulty: "Moderate",
            cognitiveSkill: "Interpretation",
            questionType: "multiple-choice",
            timeLimit: 15,
            points: 2,
            question: "On May 20, 2025, which body formally adopted the world’s first WHO Pandemic Agreement by consensus?",
            options: {
                A: "UN Security Council",
                B: "World Bank",
                C: "World Health Assembly",
                D: "International Court of Justice"
            },
            correctAnswer: "World Health Assembly",
            correctOption: "C",
            acceptedAlternativeAnswers: [],
            explanation: "The 78th World Health Assembly, WHO’s decision-making body, adopted the agreement. The other institutions did not adopt it. Event date: May 20, 2025.",
            quizMasterNote: "None.",
            sourceTitle: "World Health Assembly adopts historic Pandemic Agreement",
            sourceInstitution: "World Health Organization",
            sourceDate: "May 20, 2025",
            sourceLink: "https://www.who.int/news/item/20-05-2025-world-health-assembly-adopts-historic-pandemic-agreement-to-make-the-world-more-equitable-and-safer-from-future-pandemics"
        },
        {
            id: "R2-6",
            round: "round2",
            roundTitle: "Double the Fun",
            questionNumber: 6,
            subjectArea: "Arts and Literature",
            specificTopic: "Narrative technique—dramatic irony",
            difficulty: "Moderate",
            cognitiveSkill: "Analysis",
            questionType: "multiple-choice",
            timeLimit: 15,
            points: 2,
            question: "In a play, the audience knows that a visitor is the missing heir, but the characters welcome him as a stranger. Which device creates this effect?",
            options: {
                A: "Foreshadowing",
                B: "Flashback",
                C: "Apostrophe",
                D: "Dramatic irony"
            },
            correctAnswer: "Dramatic irony",
            correctOption: "D",
            acceptedAlternativeAnswers: [],
            explanation: "Dramatic irony occurs when the audience knows crucial information characters do not. Foreshadowing hints, flashback shifts to earlier events, and apostrophe addresses an absent entity.",
            quizMasterNote: "None.",
            sourceTitle: "Glossary of Literary Terms",
            sourceInstitution: "Poetry Foundation",
            sourceDate: "No date shown",
            sourceLink: "https://www.poetryfoundation.org/education/glossary"
        },
        {
            id: "R2-7",
            round: "round2",
            roundTitle: "Double the Fun",
            questionNumber: 7,
            subjectArea: "Social Sciences",
            specificTopic: "Sociology—symbolic interactionism",
            difficulty: "Moderate",
            cognitiveSkill: "Application",
            questionType: "multiple-choice",
            timeLimit: 15,
            points: 2,
            question: "A researcher studies how students create shared meanings through emojis in small-group chats. Which sociological perspective most directly fits?",
            options: {
                A: "Symbolic interactionism",
                B: "Structural functionalism",
                C: "Conflict theory",
                D: "Demographic transition theory"
            },
            correctAnswer: "Symbolic interactionism",
            correctOption: "A",
            acceptedAlternativeAnswers: [],
            explanation: "Symbolic interactionism examines meaning-making in face-to-face or small-scale interactions. Functionalism and conflict theory are generally macro-oriented; demographic transition explains population change.",
            quizMasterNote: "None.",
            sourceTitle: "1.3 Theoretical Perspectives in Sociology",
            sourceInstitution: "OpenStax, Rice University",
            sourceDate: "2021",
            sourceLink: "https://openstax.org/books/introduction-sociology-3e/pages/1-3-theoretical-perspectives-in-sociology"
        },
        {
            id: "R2-8",
            round: "round2",
            roundTitle: "Double the Fun",
            questionNumber: 8,
            subjectArea: "Mathematics",
            specificTopic: "Basic statistics—interquartile range",
            difficulty: "Moderate",
            cognitiveSkill: "Application",
            questionType: "multiple-choice",
            timeLimit: 15,
            points: 2,
            question: "For a data set, the first quartile is 12 and the third quartile is 27. What is the interquartile range?",
            options: {
                A: "12",
                B: "15",
                C: "27",
                D: "39"
            },
            correctAnswer: "15",
            correctOption: "B",
            acceptedAlternativeAnswers: [],
            explanation: "IQR = Q3 − Q1 = 27 − 12 = 15. The other options use a quartile alone or add the quartiles.",
            quizMasterNote: "None.",
            sourceTitle: "Introductory Statistics 2e",
            sourceInstitution: "OpenStax, Rice University",
            sourceDate: "2023",
            sourceLink: "https://openstax.org/details/books/introductory-statistics-2e"
        },
        {
            id: "R2-9",
            round: "round2",
            roundTitle: "Double the Fun",
            questionNumber: 9,
            subjectArea: "Science and Technology",
            specificTopic: "Physics—acceleration",
            difficulty: "Moderate",
            cognitiveSkill: "Application",
            questionType: "identification",
            timeLimit: 15,
            points: 2,
            question: "A bicycle’s velocity changes uniformly from 4 m/s to 10 m/s in 3 seconds. What is its acceleration in m/s squared?",
            options: null,
            correctAnswer: "2 m/s squared",
            correctOption: null,
            acceptedAlternativeAnswers: ["2 m/s^2", "2"],
            explanation: "Acceleration equals change in velocity divided by time: (10 − 4)/3 = 2 m/s squared.",
            quizMasterNote: "Accept the listed plain-text or conventional unit forms.",
            sourceTitle: "College Physics 2e",
            sourceInstitution: "OpenStax, Rice University",
            sourceDate: "2022",
            sourceLink: "https://openstax.org/details/books/college-physics-2e"
        },
        {
            id: "R2-10",
            round: "round2",
            roundTitle: "Double the Fun",
            questionNumber: 10,
            subjectArea: "General Information",
            specificTopic: "Expo 2025 Osaka, Kansai",
            difficulty: "Moderate",
            cognitiveSkill: "Recall and interpretation",
            questionType: "identification",
            timeLimit: 15,
            points: 2,
            question: "Expo 2025 opened to the public on April 13, 2025 on Yumeshima. In which Japanese city is Yumeshima located?",
            options: null,
            correctAnswer: "Osaka",
            correctOption: null,
            acceptedAlternativeAnswers: ["Osaka City"],
            explanation: "Yumeshima, the Expo venue, is in Osaka; the event is officially Expo 2025 Osaka, Kansai, Japan. Event date: April 13, 2025.",
            quizMasterNote: "None.",
            sourceTitle: "Declaration of Opening and Ribbon-Cutting Ceremony",
            sourceInstitution: "Japan Association for the 2025 World Exposition",
            sourceDate: "February 25, 2025",
            sourceLink: "https://www.expo2025.or.jp/en/news/news-20250225-07/"
        }
    ],
    round3: [
        {
            id: "R3-1",
            round: "round3",
            roundTitle: "Triple Treat",
            questionNumber: 1,
            subjectArea: "Arts and Literature",
            specificTopic: "Narrative reliability",
            difficulty: "Difficult",
            cognitiveSkill: "Evaluation",
            questionType: "multiple-choice",
            timeLimit: 20,
            points: 3,
            question: "A first-person narrator repeatedly contradicts verifiable events and admits concealing facts. Which reading strategy is most justified?",
            options: {
                A: "Treat every statement as objective fact",
                B: "Evaluate the narrator as potentially unreliable",
                C: "Assume the author and narrator are identical",
                D: "Ignore all plot events outside dialogue"
            },
            correctAnswer: "Evaluate the narrator as potentially unreliable",
            correctOption: "B",
            acceptedAlternativeAnswers: [],
            explanation: "Contradictions and admitted concealment justify testing the narrator’s reliability against textual evidence. The other options make unsupported assumptions or discard relevant evidence.",
            quizMasterNote: "None.",
            sourceTitle: "Glossary of Literary Terms",
            sourceInstitution: "Poetry Foundation",
            sourceDate: "No date shown",
            sourceLink: "https://www.poetryfoundation.org/education/glossary"
        },
        {
            id: "R3-2",
            round: "round3",
            roundTitle: "Triple Treat",
            questionNumber: 2,
            subjectArea: "Social Sciences",
            specificTopic: "Political science—checks and balances",
            difficulty: "Difficult",
            cognitiveSkill: "Integration and evaluation",
            questionType: "multiple-choice",
            timeLimit: 20,
            points: 3,
            question: "A legislature passes a bill, the executive vetoes it, and the legislature overrides the veto by the constitutionally required supermajority. Which principle is most directly illustrated?",
            options: {
                A: "Unitary government",
                B: "Direct democracy",
                C: "Checks and balances",
                D: "Judicial supremacy"
            },
            correctAnswer: "Checks and balances",
            correctOption: "C",
            acceptedAlternativeAnswers: [],
            explanation: "Each branch can limit another: executive veto and legislative override are reciprocal checks. The sequence does not describe the other concepts.",
            quizMasterNote: "None.",
            sourceTitle: "Separation of Powers Under the Constitution",
            sourceInstitution: "Congress.gov, Library of Congress",
            sourceDate: "No date shown",
            sourceLink: "https://constitution.congress.gov/browse/essay/intro.7-2/ALDE_00000031/"
        },
        {
            id: "R3-3",
            round: "round3",
            roundTitle: "Triple Treat",
            questionNumber: 3,
            subjectArea: "Mathematics",
            specificTopic: "Weighted mean",
            difficulty: "Difficult",
            cognitiveSkill: "Multi-step reasoning",
            questionType: "multiple-choice",
            timeLimit: 20,
            points: 3,
            question: "Class A has 20 students with a mean score of 80. Class B has 30 students with a mean score of 90. What is the combined mean score?",
            options: {
                A: "84",
                B: "85",
                C: "88",
                D: "86"
            },
            correctAnswer: "86",
            correctOption: "D",
            acceptedAlternativeAnswers: [],
            explanation: "Total points are 20(80)+30(90)=4300 across 50 students; 4300/50=86. Averaging 80 and 90 directly would wrongly give 85.",
            quizMasterNote: "None.",
            sourceTitle: "Introductory Statistics 2e",
            sourceInstitution: "OpenStax, Rice University",
            sourceDate: "2023",
            sourceLink: "https://openstax.org/details/books/introductory-statistics-2e"
        },
        {
            id: "R3-4",
            round: "round3",
            roundTitle: "Triple Treat",
            questionNumber: 4,
            subjectArea: "Science and Technology",
            specificTopic: "Biology—test cross",
            difficulty: "Difficult",
            cognitiveSkill: "Multi-step reasoning",
            questionType: "multiple-choice",
            timeLimit: 20,
            points: 3,
            question: "In a species, tallness (T) is dominant over shortness (t). A tall plant crossed with a short plant produces equal numbers of tall and short offspring. What is the tall parent’s genotype?",
            options: {
                A: "Tt",
                B: "TT",
                C: "tt",
                D: "Cannot be determined"
            },
            correctAnswer: "Tt",
            correctOption: "A",
            acceptedAlternativeAnswers: [],
            explanation: "The short parent is tt. A 1:1 tall-to-short ratio results from Tt × tt. TT × tt gives all tall, while tt is not tall.",
            quizMasterNote: "None.",
            sourceTitle: "Biology 2e",
            sourceInstitution: "OpenStax, Rice University",
            sourceDate: "2020",
            sourceLink: "https://openstax.org/details/books/biology-2e"
        },
        {
            id: "R3-5",
            round: "round3",
            roundTitle: "Triple Treat",
            questionNumber: 5,
            subjectArea: "General Information",
            specificTopic: "2024 Nobel Prize in Chemistry",
            difficulty: "Difficult",
            cognitiveSkill: "Integration",
            questionType: "multiple-choice",
            timeLimit: 20,
            points: 3,
            question: "The 2024 Nobel Prize in Chemistry recognized David Baker for computational protein design. Demis Hassabis and John Jumper shared the other half for what achievement?",
            options: {
                A: "CRISPR gene editing",
                B: "Protein structure prediction",
                C: "mRNA vaccine delivery",
                D: "Quantum-dot synthesis"
            },
            correctAnswer: "Protein structure prediction",
            correctOption: "B",
            acceptedAlternativeAnswers: [],
            explanation: "Hassabis and Jumper were honored for protein structure prediction; the other achievements were not their cited 2024 award contribution. Event date: October 9, 2024.",
            quizMasterNote: "None.",
            sourceTitle: "Press release: Nobel Prize in Chemistry 2024",
            sourceInstitution: "Royal Swedish Academy of Sciences / Nobel Prize Outreach",
            sourceDate: "October 9, 2024",
            sourceLink: "https://www.nobelprize.org/prizes/chemistry/2024/press-release/"
        },
        {
            id: "R3-6",
            round: "round3",
            roundTitle: "Triple Treat",
            questionNumber: 6,
            subjectArea: "Arts and Literature",
            specificTopic: "Intertextuality",
            difficulty: "Difficult",
            cognitiveSkill: "Synthesis",
            questionType: "multiple-choice",
            timeLimit: 20,
            points: 3,
            question: "A contemporary poem retells the Odyssey from Penelope’s viewpoint and gains meaning through readers’ knowledge of the earlier epic. Which concept best describes this relationship?",
            options: {
                A: "Onomatopoeia",
                B: "Verisimilitude",
                C: "Intertextuality",
                D: "Denouement"
            },
            correctAnswer: "Intertextuality",
            correctOption: "C",
            acceptedAlternativeAnswers: [],
            explanation: "Intertextuality is meaning generated through a text’s relation to another text. The distractors concern sound imitation, lifelikeness, and plot resolution.",
            quizMasterNote: "None.",
            sourceTitle: "Glossary of Literary Terms",
            sourceInstitution: "Poetry Foundation",
            sourceDate: "No date shown",
            sourceLink: "https://www.poetryfoundation.org/education/glossary"
        },
        {
            id: "R3-7",
            round: "round3",
            roundTitle: "Triple Treat",
            questionNumber: 7,
            subjectArea: "Social Sciences",
            specificTopic: "Psychology—classical conditioning",
            difficulty: "Difficult",
            cognitiveSkill: "Application and integration",
            questionType: "multiple-choice",
            timeLimit: 20,
            points: 3,
            question: "A tone is repeatedly sounded just before food makes a dog salivate. Later, the tone alone produces salivation. After conditioning, what is the tone?",
            options: {
                A: "Unconditioned response",
                B: "Unconditioned stimulus",
                C: "Conditioned response",
                D: "Conditioned stimulus"
            },
            correctAnswer: "Conditioned stimulus",
            correctOption: "D",
            acceptedAlternativeAnswers: [],
            explanation: "The formerly neutral tone becomes the conditioned stimulus; salivation to it is the conditioned response. Food is the unconditioned stimulus.",
            quizMasterNote: "None.",
            sourceTitle: "6.2 Classical Conditioning",
            sourceInstitution: "OpenStax, Rice University",
            sourceDate: "2020",
            sourceLink: "https://openstax.org/books/psychology-2e/pages/6-2-classical-conditioning"
        },
        {
            id: "R3-8",
            round: "round3",
            roundTitle: "Triple Treat",
            questionNumber: 8,
            subjectArea: "Mathematics",
            specificTopic: "Standard deviation under transformation",
            difficulty: "Difficult",
            cognitiveSkill: "Analysis",
            questionType: "multiple-choice",
            timeLimit: 20,
            points: 3,
            question: "Every value in a data set is multiplied by 3 and then increased by 5. If the original standard deviation is 4, what is the new standard deviation?",
            options: {
                A: "12",
                B: "17",
                C: "9",
                D: "7"
            },
            correctAnswer: "12",
            correctOption: "A",
            acceptedAlternativeAnswers: [],
            explanation: "Multiplying all values by 3 multiplies standard deviation by 3; adding 5 changes location but not spread. Thus 3(4)=12.",
            quizMasterNote: "None.",
            sourceTitle: "Introductory Statistics 2e",
            sourceInstitution: "OpenStax, Rice University",
            sourceDate: "2023",
            sourceLink: "https://openstax.org/details/books/introductory-statistics-2e"
        },
        {
            id: "R3-9",
            round: "round3",
            roundTitle: "Triple Treat",
            questionNumber: 9,
            subjectArea: "Science and Technology",
            specificTopic: "Earth science—plate boundaries",
            difficulty: "Difficult",
            cognitiveSkill: "Integration",
            questionType: "identification",
            timeLimit: 20,
            points: 3,
            question: "At a boundary, two plates slide horizontally past each other, and crust is neither created nor destroyed. Name this boundary type.",
            options: null,
            correctAnswer: "Transform boundary",
            correctOption: null,
            acceptedAlternativeAnswers: ["Transform plate boundary", "Transform fault boundary"],
            explanation: "USGS distinguishes transform boundaries by horizontal sliding with neither crust production nor destruction.",
            quizMasterNote: "None.",
            sourceTitle: "Understanding Plate Motions",
            sourceInstitution: "U.S. Geological Survey",
            sourceDate: "No date shown",
            sourceLink: "https://pubs.usgs.gov/gip/dynamic/understanding.html"
        },
        {
            id: "R3-10",
            round: "round3",
            roundTitle: "Triple Treat",
            questionNumber: 10,
            subjectArea: "General Information",
            specificTopic: "COP29 climate-finance agreement",
            difficulty: "Difficult",
            cognitiveSkill: "Recall and integration",
            questionType: "identification",
            timeLimit: 20,
            points: 3,
            question: "At COP29 on November 24, 2024, countries agreed to triple annual climate finance for developing countries by 2035. State the new annual target in US dollars.",
            options: null,
            correctAnswer: "USD 300 billion per year",
            correctOption: null,
            acceptedAlternativeAnswers: ["US$300 billion annually", "300 billion US dollars per year", "USD 300 billion annually"],
            explanation: "USD 300 billion per year won the men’s floor exercise gold, the Philippines’ first Olympic medal in gymnastics. Event date: November 24, 2024.",
            quizMasterNote: "None.",
            sourceTitle: "USD 300 billion per year delivers historic floor exercise gold",
            sourceInstitution: "UN Climate Change / UNFCCC",
            sourceDate: "November 24, 2024",
            sourceLink: "https://www.olympics.com/en/news/carlos-yulo-delivers-clutch-routine-for-historic-floor-exercise-gold-medal"
        }
    ],
    tieBreakers: [
        {
            id: "TB-1",
            round: "tieBreakers",
            roundTitle: "Tie-Breaker",
            questionNumber: 1,
            subjectArea: "Mathematics",
            specificTopic: "Number theory",
            difficulty: "Moderate",
            cognitiveSkill: "Multi-step reasoning",
            questionType: "identification",
            timeLimit: 20,
            points: 0,
            question: "What is the least positive integer divisible by 6, 8, and 15?",
            options: null,
            correctAnswer: "120",
            correctOption: null,
            acceptedAlternativeAnswers: [],
            explanation: "Prime factors needed are 2 cubed, 3, and 5; their product is 120.",
            quizMasterNote: "None.",
            sourceTitle: "Elementary Algebra 2e",
            sourceInstitution: "OpenStax, Rice University",
            sourceDate: "2020",
            sourceLink: "https://openstax.org/details/books/elementary-algebra-2e"
        },
        {
            id: "TB-2",
            round: "tieBreakers",
            roundTitle: "Tie-Breaker",
            questionNumber: 2,
            subjectArea: "Science and Technology",
            specificTopic: "Physics—momentum",
            difficulty: "Moderate",
            cognitiveSkill: "Application",
            questionType: "multiple-choice",
            timeLimit: 15,
            points: 0,
            question: "Two carts have equal momentum. Cart X has twice the mass of Cart Y. How does X’s speed compare with Y’s?",
            options: {
                A: "Twice as great",
                B: "Equal",
                C: "Half as great",
                D: "Four times as great"
            },
            correctAnswer: "Half as great",
            correctOption: "C",
            acceptedAlternativeAnswers: [],
            explanation: "Since momentum p=mv is equal, doubling mass requires halving speed. The other relationships do not preserve equal momentum.",
            quizMasterNote: "None.",
            sourceTitle: "College Physics 2e",
            sourceInstitution: "OpenStax, Rice University",
            sourceDate: "2022",
            sourceLink: "https://openstax.org/details/books/college-physics-2e"
        },
        {
            id: "TB-3",
            round: "tieBreakers",
            roundTitle: "Tie-Breaker",
            questionNumber: 3,
            subjectArea: "Social Sciences",
            specificTopic: "Economics—scarcity",
            difficulty: "Easy",
            cognitiveSkill: "Application",
            questionType: "multiple-choice",
            timeLimit: 10,
            points: 0,
            question: "A city has unlimited wants but limited land, labor, and funds. Which economic condition does this describe?",
            options: {
                A: "Scarcity",
                B: "Inflation",
                C: "Monopoly",
                D: "Surplus"
            },
            correctAnswer: "Scarcity",
            correctOption: "A",
            acceptedAlternativeAnswers: [],
            explanation: "Scarcity is the condition of limited resources relative to wants. The alternatives concern price change, market structure, or excess supply.",
            quizMasterNote: "None.",
            sourceTitle: "Principles of Economics 3e, Chapter 2",
            sourceInstitution: "OpenStax, Rice University",
            sourceDate: "2022",
            sourceLink: "https://openstax.org/books/principles-economics-3e/pages/2-introduction-to-choice-in-a-world-of-scarcity"
        },
        {
            id: "TB-4",
            round: "tieBreakers",
            roundTitle: "Tie-Breaker",
            questionNumber: 4,
            subjectArea: "Arts and Literature",
            specificTopic: "Art appreciation—Cubism",
            difficulty: "Difficult",
            cognitiveSkill: "Comparison",
            questionType: "identification",
            timeLimit: 20,
            points: 0,
            question: "Name the Cubist phase, beginning after 1912, associated with combining forms, stronger color, and collage.",
            options: null,
            correctAnswer: "Synthetic Cubism",
            correctOption: null,
            acceptedAlternativeAnswers: [],
            explanation: "Synthetic Cubism emphasized combining forms and often incorporated collage, unlike the earlier Analytical phase.",
            quizMasterNote: "None.",
            sourceTitle: "Cubism",
            sourceInstitution: "Encyclopaedia Britannica",
            sourceDate: "July 29, 2026",
            sourceLink: "https://www.britannica.com/art/Cubism"
        },
        {
            id: "TB-5",
            round: "tieBreakers",
            roundTitle: "Tie-Breaker",
            questionNumber: 5,
            subjectArea: "General Information",
            specificTopic: "UNESCO World Heritage 2025",
            difficulty: "Moderate",
            cognitiveSkill: "Recall and interpretation",
            questionType: "multiple-choice",
            timeLimit: 15,
            points: 0,
            question: "On July 17, 2025, UNESCO reported how many new properties had been inscribed at the 47th World Heritage Committee session?",
            options: {
                A: "20",
                B: "24",
                C: "25",
                D: "26"
            },
            correctAnswer: "26",
            correctOption: "D",
            acceptedAlternativeAnswers: [],
            explanation: "UNESCO reported 26 new cultural and natural properties. The other figures do not match the official session report. Event date: July 17, 2025.",
            quizMasterNote: "None.",
            sourceTitle: "UNESCO World Heritage: 26 new sites inscribed",
            sourceInstitution: "UNESCO",
            sourceDate: "July 17, 2025",
            sourceLink: "https://www.unesco.org/en/articles/unesco-world-heritage-26-new-sites-inscribed-0"
        }
    ]
};