// SAMPLE DATA ONLY - DO NOT PUT OFFICIAL COMPETITION QUESTIONS HERE
const sampleQuizData = {
    trial: [
        {
            id: "T1",
            round: "trial",
            roundTitle: "Trial Questions",
            questionNumber: 1,
            subjectArea: "Mathematics",
            specificTopic: "Basic Operations",
            difficulty: "Easy",
            cognitiveSkill: "Application",
            questionType: "multiple-choice",
            timeLimit: 10,
            points: 0,
            question: "Evaluate 6 + 2 × 3.",
            options: { A: "24", B: "12", C: "18", D: "8" },
            correctAnswer: "12",
            correctOption: "B",
            acceptedAlternativeAnswers: [],
            explanation: "According to the order of operations (PEMDAS), multiplication is performed first. 2 × 3 = 6, and 6 + 6 = 12.",
            quizMasterNote: "Remind teams about PEMDAS if necessary.",
            sourceTitle: "Basic Math Rules",
            sourceInstitution: "Sample Inst",
            sourceDate: "2026",
            sourceLink: ""
        },
        {
            id: "T2",
            round: "trial",
            roundTitle: "Trial Questions",
            questionNumber: 2,
            subjectArea: "Geography",
            specificTopic: "Capitals",
            difficulty: "Easy",
            cognitiveSkill: "Recall",
            questionType: "identification",
            timeLimit: 15,
            points: 0,
            question: "What is the capital city of Japan?",
            options: null,
            correctAnswer: "Tokyo",
            correctOption: null,
            acceptedAlternativeAnswers: ["Tokyo City", "Metropolis of Tokyo"],
            explanation: "Tokyo has been the de facto capital of Japan since 1868.",
            quizMasterNote: "Accept 'Tokyo' only.",
            sourceTitle: "World Atlas",
            sourceInstitution: "Sample Inst",
            sourceDate: "2026",
            sourceLink: ""
        }
    ],
    round1: [
        {
            id: "R1-1",
            round: "round1",
            roundTitle: "Once and For All",
            questionNumber: 1,
            subjectArea: "Science",
            specificTopic: "Biology",
            difficulty: "Easy",
            cognitiveSkill: "Recognition",
            questionType: "multiple-choice",
            timeLimit: 10,
            points: 1,
            question: "Which organelle is known as the powerhouse of the cell?",
            options: { A: "Nucleus", B: "Ribosome", C: "Mitochondria", D: "Chloroplast" },
            correctAnswer: "Mitochondria",
            correctOption: "C",
            acceptedAlternativeAnswers: [],
            explanation: "Mitochondria generate most of the chemical energy needed to power the cell's biochemical reactions.",
            quizMasterNote: "None.",
            sourceTitle: "Biology 101",
            sourceInstitution: "",
            sourceDate: "",
            sourceLink: ""
        },
        {
            id: "R1-2",
            round: "round1",
            roundTitle: "Once and For All",
            questionNumber: 2,
            subjectArea: "History",
            specificTopic: "Ancient Inventions",
            difficulty: "Easy",
            cognitiveSkill: "Recall",
            questionType: "identification",
            timeLimit: 10,
            points: 1,
            question: "Who is traditionally credited with inventing the printing press in Europe?",
            options: null,
            correctAnswer: "Johannes Gutenberg",
            correctOption: null,
            acceptedAlternativeAnswers: ["Gutenberg"],
            explanation: "Johannes Gutenberg introduced letterpress printing to Europe with his movable type printing press.",
            quizMasterNote: "Accept just the last name.",
            sourceTitle: "History Book",
            sourceInstitution: "",
            sourceDate: "",
            sourceLink: ""
        }
    ],
    round2: [
        {
            id: "R2-1",
            round: "round2",
            roundTitle: "Double the Fun",
            questionNumber: 1,
            subjectArea: "Physics",
            specificTopic: "Thermodynamics",
            difficulty: "Moderate",
            cognitiveSkill: "Analysis",
            questionType: "multiple-choice",
            timeLimit: 15,
            points: 2,
            question: "Which law of thermodynamics states that entropy of an isolated system always increases over time?",
            options: { A: "Zeroth Law", B: "First Law", C: "Second Law", D: "Third Law" },
            correctAnswer: "Second Law",
            correctOption: "C",
            acceptedAlternativeAnswers: [],
            explanation: "The Second Law of Thermodynamics dictates that total entropy can never decrease over time for an isolated system.",
            quizMasterNote: "None.",
            sourceTitle: "Physics Textbook",
            sourceInstitution: "",
            sourceDate: "",
            sourceLink: ""
        },
        {
            id: "R2-2",
            round: "round2",
            roundTitle: "Double the Fun",
            questionNumber: 2,
            subjectArea: "Literature",
            specificTopic: "Shakespeare",
            difficulty: "Moderate",
            cognitiveSkill: "Interpretation",
            questionType: "identification",
            timeLimit: 15,
            points: 2,
            question: "In Shakespeare's 'Macbeth', what title does Macbeth hold at the very beginning of the play before meeting the witches?",
            options: null,
            correctAnswer: "Thane of Glamis",
            correctOption: null,
            acceptedAlternativeAnswers: ["Glamis"],
            explanation: "He is already the Thane of Glamis. He is later made Thane of Cawdor.",
            quizMasterNote: "Do not accept Thane of Cawdor.",
            sourceTitle: "Complete Works",
            sourceInstitution: "",
            sourceDate: "",
            sourceLink: ""
        }
    ],
    round3: [
        {
            id: "R3-1",
            round: "round3",
            roundTitle: "Triple Treat",
            questionNumber: 1,
            subjectArea: "Chemistry",
            specificTopic: "Organic Synthesis",
            difficulty: "Difficult",
            cognitiveSkill: "Multi-step reasoning",
            questionType: "multiple-choice",
            timeLimit: 20,
            points: 3,
            question: "When benzene undergoes nitration followed by reduction with Sn/HCl, what is the final major organic product?",
            options: { A: "Nitrobenzene", B: "Aniline", C: "Phenol", D: "Toluene" },
            correctAnswer: "Aniline",
            correctOption: "B",
            acceptedAlternativeAnswers: [],
            explanation: "Nitration of benzene yields nitrobenzene. Reduction of nitrobenzene with Tin and Hydrochloric acid yields aniline.",
            quizMasterNote: "Ensure chemical names are clear.",
            sourceTitle: "Organic Chem Guide",
            sourceInstitution: "",
            sourceDate: "",
            sourceLink: ""
        },
        {
            id: "R3-2",
            round: "round3",
            roundTitle: "Triple Treat",
            questionNumber: 2,
            subjectArea: "Economics",
            specificTopic: "Market Structures",
            difficulty: "Difficult",
            cognitiveSkill: "Synthesis",
            questionType: "identification",
            timeLimit: 20,
            points: 3,
            question: "What term describes a market structure in which a small number of interdependent firms compete?",
            options: null,
            correctAnswer: "Oligopoly",
            correctOption: null,
            acceptedAlternativeAnswers: ["Oligopolistic market"],
            explanation: "An oligopoly consists of a few dominant sellers that are highly aware of each other's actions.",
            quizMasterNote: "Spelling must be strictly accurate.",
            sourceTitle: "Econ 201",
            sourceInstitution: "",
            sourceDate: "",
            sourceLink: ""
        }
    ],
    tieBreakers: [
        {
            id: "TB-1",
            round: "tieBreakers",
            roundTitle: "Tie-Breaker",
            questionNumber: 1,
            subjectArea: "General Knowledge",
            specificTopic: "Space",
            difficulty: "Difficult",
            cognitiveSkill: "Recall",
            questionType: "multiple-choice",
            timeLimit: 12,
            points: 0,
            question: "Which planet in our solar system has the most moons?",
            options: { A: "Jupiter", B: "Saturn", C: "Uranus", D: "Neptune" },
            correctAnswer: "Saturn",
            correctOption: "B",
            acceptedAlternativeAnswers: [],
            explanation: "Saturn surpassed Jupiter with the discovery of numerous additional small moons.",
            quizMasterNote: "Tie-breakers are sudden death.",
            sourceTitle: "Astronomy Today",
            sourceInstitution: "",
            sourceDate: "",
            sourceLink: ""
        },
        {
            id: "TB-2",
            round: "tieBreakers",
            roundTitle: "Tie-Breaker",
            questionNumber: 2,
            subjectArea: "Pop Culture",
            specificTopic: "Movies",
            difficulty: "Moderate",
            cognitiveSkill: "Recall",
            questionType: "identification",
            timeLimit: 15,
            points: 0,
            question: "Which movie won the Academy Award for Best Picture in 1994?",
            options: null,
            correctAnswer: "Forrest Gump",
            correctOption: null,
            acceptedAlternativeAnswers: [],
            explanation: "Forrest Gump defeated Pulp Fiction and The Shawshank Redemption.",
            quizMasterNote: "Sudden death.",
            sourceTitle: "Oscars Archive",
            sourceInstitution: "",
            sourceDate: "",
            sourceLink: ""
        }
    ]
};